//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gBankerBUROAPIEntities : DbContext
    {
        public gBankerBUROAPIEntities()
            : base("name=gBankerBUROAPIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BKashUserCheck> BKashUserCheck { get; set; }
        public virtual DbSet<BKashAPILOG> BKashAPILOG { get; set; }
        public virtual DbSet<BKashAPIParking> BKashAPIParking { get; set; }
    }
}
