using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace gBanker.Data.DBDetailModels.OLRSHubs.OLRSHubPayloads
{
    public class PRA_MN_IMP_COST_LN_SC_Model
    {
        public string PO_CODE { get; set; }
        public string MNYR { get; set; }
        public decimal SC_RATE { get; set; }
        public decimal? LOAN_00 { get; set; }
        public decimal? LOAN_01 { get; set; }
        public decimal? LOAN_02 { get; set; }
        public decimal? LOAN_03 { get; set; }
        public decimal? LOAN_04 { get; set; }
        public decimal? LOAN_05 { get; set; }
        public decimal? LOAN_06 { get; set; }
        public decimal? LOAN_07 { get; set; }
        public decimal? LOAN_08 { get; set; }
        public decimal? LOAN_09 { get; set; }
        public decimal? LOAN_10 { get; set; }
        public decimal? LOAN_11 { get; set; }
        public decimal? LOAN_12 { get; set; }
        public decimal? LOAN_13 { get; set; }
        public decimal? LOAN_14 { get; set; }
        public decimal? LOAN_15 { get; set; }
        public decimal? LOAN_16 { get; set; }
        public decimal? LOAN_17 { get; set; }
        public decimal? LOAN_18 { get; set; }
        public decimal? LOAN_19 { get; set; }
        public decimal? LOAN_20 { get; set; }
        public decimal? LOAN_21 { get; set; }
        public decimal? LOAN_22 { get; set; }
        public decimal? LOAN_23 { get; set; }
        public decimal? LOAN_24 { get; set; }
        public decimal? LOAN_25 { get; set; }
        public decimal? LOAN_26 { get; set; }
        public decimal? LOAN_27 { get; set; }
        public decimal? LOAN_28 { get; set; }
        public decimal? LOAN_29 { get; set; }
        public decimal? LOAN_30 { get; set; }
        public decimal? LOAN_31 { get; set; }
        public decimal? LOAN_32 { get; set; }
        public decimal? LOAN_33 { get; set; }
        public decimal? LOAN_34 { get; set; }
        public decimal? LOAN_35 { get; set; }
        public decimal? LOAN_36 { get; set; }
        public decimal? LOAN_37 { get; set; }
        public decimal? LOAN_38 { get; set; }
        public decimal? LOAN_39 { get; set; }
        public decimal? LOAN_40 { get; set; }
        public decimal? LOAN_41 { get; set; }
        public decimal? LOAN_42 { get; set; }
        public decimal? LOAN_43 { get; set; }
        public decimal? LOAN_44 { get; set; }
        public decimal? LOAN_45 { get; set; }
        public decimal? LOAN_46 { get; set; }
        public decimal? LOAN_47 { get; set; }
        public decimal? LOAN_48 { get; set; }
        public decimal? LOAN_49 { get; set; }
        public decimal? LOAN_50 { get; set; }
        public decimal? LOAN_51 { get; set; }
        public decimal? LOAN_52 { get; set; }
        public decimal? LOAN_53 { get; set; }
        public decimal? LOAN_54 { get; set; }
        public decimal? LOAN_55 { get; set; }
        public decimal? LOAN_56 { get; set; }
        public decimal? LOAN_57 { get; set; }
        public decimal? LOAN_58 { get; set; }
        public decimal? LOAN_59 { get; set; }
        public decimal? LOAN_60 { get; set; }
        public decimal? LOAN_61 { get; set; }
        public decimal? LOAN_62 { get; set; }
        public decimal? LOAN_63 { get; set; }
        public decimal? LOAN_64 { get; set; }
        public decimal? LOAN_65 { get; set; }
        public decimal? LOAN_66 { get; set; }
        public decimal? LOAN_67 { get; set; }
        public decimal? LOAN_68 { get; set; }
        public decimal? LOAN_69 { get; set; }
        public decimal? LOAN_70 { get; set; }
        public decimal? LOAN_71 { get; set; }
        public decimal? LOAN_72 { get; set; }
        public decimal? LOAN_73 { get; set; }
        public decimal? LOAN_74 { get; set; }
        public decimal? LOAN_75 { get; set; }
        public decimal? LOAN_76 { get; set; }
        public decimal? LOAN_77 { get; set; }
        public decimal? LOAN_78 { get; set; }
        public decimal? LOAN_79 { get; set; }
        public decimal? LOAN_80 { get; set; }
        public decimal? LOAN_81 { get; set; }
        public decimal? LOAN_82 { get; set; }
        public decimal? LOAN_83 { get; set; }
        public decimal? LOAN_84 { get; set; }
        public decimal? LOAN_85 { get; set; }
        public decimal? LOAN_86 { get; set; }
        public decimal? LOAN_87 { get; set; }
        public decimal? LOAN_88 { get; set; }
        public decimal? LOAN_89 { get; set; }
        public decimal? LOAN_90 { get; set; }
        public decimal? LOAN_91 { get; set; }
        public decimal? LOAN_92 { get; set; }
        public decimal? LOAN_93 { get; set; }
        public decimal? LOAN_94 { get; set; }
        public decimal? LOAN_95 { get; set; }
        public decimal? LOAN_96 { get; set; }
        public decimal? LOAN_97 { get; set; }
        public decimal? LOAN_98 { get; set; }
        public decimal? LOAN_99 { get; set; }
        public decimal? LOAN_100 { get; set; }
        public Int64? LOAN_CAL_00 { get; set; }
        public Int64? LOAN_CAL_01 { get; set; }
        public Int64? LOAN_CAL_02 { get; set; }
        public Int64? LOAN_CAL_03 { get; set; }
        public Int64? LOAN_CAL_04 { get; set; }
        public Int64? LOAN_CAL_05 { get; set; }
        public Int64? LOAN_CAL_06 { get; set; }
        public Int64? LOAN_CAL_07 { get; set; }
        public Int64? LOAN_CAL_08 { get; set; }
        public Int64? LOAN_CAL_09 { get; set; }
        public Int64? LOAN_CAL_10 { get; set; }
        public Int64? LOAN_CAL_11 { get; set; }
        public Int64? LOAN_CAL_12 { get; set; }
        public Int64? LOAN_CAL_13 { get; set; }
        public Int64? LOAN_CAL_14 { get; set; }
        public Int64? LOAN_CAL_15 { get; set; }
        public Int64? LOAN_CAL_16 { get; set; }
        public Int64? LOAN_CAL_17 { get; set; }
        public Int64? LOAN_CAL_18 { get; set; }
        public Int64? LOAN_CAL_19 { get; set; }
        public Int64? LOAN_CAL_20 { get; set; }
        public Int64? LOAN_CAL_21 { get; set; }
        public Int64? LOAN_CAL_22 { get; set; }
        public Int64? LOAN_CAL_23 { get; set; }
        public Int64? LOAN_CAL_24 { get; set; }
        public Int64? LOAN_CAL_25 { get; set; }
        public Int64? LOAN_CAL_26 { get; set; }
        public Int64? LOAN_CAL_27 { get; set; }
        public Int64? LOAN_CAL_28 { get; set; }
        public Int64? LOAN_CAL_29 { get; set; }
        public Int64? LOAN_CAL_30 { get; set; }
        public Int64? LOAN_CAL_31 { get; set; }
        public Int64? LOAN_CAL_32 { get; set; }
        public Int64? LOAN_CAL_33 { get; set; }
        public Int64? LOAN_CAL_34 { get; set; }
        public Int64? LOAN_CAL_35 { get; set; }
        public Int64? LOAN_CAL_36 { get; set; }
        public Int64? LOAN_CAL_37 { get; set; }
        public Int64? LOAN_CAL_38 { get; set; }
        public Int64? LOAN_CAL_39 { get; set; }
        public Int64? LOAN_CAL_40 { get; set; }
        public Int64? LOAN_CAL_41 { get; set; }
        public Int64? LOAN_CAL_42 { get; set; }
        public Int64? LOAN_CAL_43 { get; set; }
        public Int64? LOAN_CAL_44 { get; set; }
        public Int64? LOAN_CAL_45 { get; set; }
        public Int64? LOAN_CAL_46 { get; set; }
        public Int64? LOAN_CAL_47 { get; set; }
        public Int64? LOAN_CAL_48 { get; set; }
        public Int64? LOAN_CAL_49 { get; set; }
        public Int64? LOAN_CAL_50 { get; set; }
        public decimal? LOAN_TOTAL { get; set; }
        public decimal? LOAN_CAL_TOTAL { get; set; }
        public string INS_USER { get; set; }
        public DateTime? INS_DATE { get; set; }
        public string UPD_USER { get; set; }
        public DateTime? UPD_DATE { get; set; }

        public Int64? LOAN_CAL_51 { get; set; }
        public Int64? LOAN_CAL_52 { get; set; }
        public Int64? LOAN_CAL_53 { get; set; }
        public Int64? LOAN_CAL_54 { get; set; }
        public Int64? LOAN_CAL_55 { get; set; }
        public Int64? LOAN_CAL_56 { get; set; }
        public Int64? LOAN_CAL_57 { get; set; }
        public Int64? LOAN_CAL_58 { get; set; }
        public Int64? LOAN_CAL_59 { get; set; }
        public Int64? LOAN_CAL_60 { get; set; }
        public string POSTING_FLAG { get; set; }
        public DateTime? STATUS_DATE { get; set; }


        //additional
        public string INS_DATE_IN_TEXT { get; set; }
        public string STATUS_DATE_IN_TEXT { get; set; }
        public string SYNCED_STATUS { get; set; }
        public int TotalCount { get; set; }


        public string LOAN_00_INFO { get; set; }
        public string LOAN_01_INFO { get; set; }
        public string LOAN_02_INFO { get; set; }
        public string LOAN_03_INFO { get; set; }
        public string LOAN_04_INFO { get; set; }
        public string LOAN_05_INFO { get; set; }
        public string LOAN_06_INFO { get; set; }
        public string LOAN_07_INFO { get; set; }
        public string LOAN_08_INFO { get; set; }
        public string LOAN_09_INFO { get; set; }
        public string LOAN_10_INFO { get; set; }
        public string LOAN_11_INFO { get; set; }
        public string LOAN_12_INFO { get; set; }
        public string LOAN_13_INFO { get; set; }
        public string LOAN_14_INFO { get; set; }
        public string LOAN_15_INFO { get; set; }
        public string LOAN_16_INFO { get; set; }
        public string LOAN_17_INFO { get; set; }
        public string LOAN_18_INFO { get; set; }
        public string LOAN_19_INFO { get; set; }
        public string LOAN_20_INFO { get; set; }
        public string LOAN_21_INFO { get; set; }
        public string LOAN_22_INFO { get; set; }
        public string LOAN_23_INFO { get; set; }
        public string LOAN_24_INFO { get; set; }
        public string LOAN_25_INFO { get; set; }
        public string LOAN_26_INFO { get; set; }
        public string LOAN_27_INFO { get; set; }
        public string LOAN_28_INFO { get; set; }
        public string LOAN_29_INFO { get; set; }
        public string LOAN_30_INFO { get; set; }
        public string LOAN_31_INFO { get; set; }
        public string LOAN_32_INFO { get; set; }
        public string LOAN_33_INFO { get; set; }
        public string LOAN_34_INFO { get; set; }
        public string LOAN_35_INFO { get; set; }
        public string LOAN_36_INFO { get; set; }
        public string LOAN_37_INFO { get; set; }
        public string LOAN_38_INFO { get; set; }
        public string LOAN_39_INFO { get; set; }
        public string LOAN_40_INFO { get; set; }
        public string LOAN_41_INFO { get; set; }
        public string LOAN_42_INFO { get; set; }
        public string LOAN_43_INFO { get; set; }
        public string LOAN_44_INFO { get; set; }
        public string LOAN_45_INFO { get; set; }
        public string LOAN_46_INFO { get; set; }
        public string LOAN_47_INFO { get; set; }
        public string LOAN_48_INFO { get; set; }
        public string LOAN_49_INFO { get; set; }
        public string LOAN_50_INFO { get; set; }
        public string LOAN_51_INFO { get; set; }
        public string LOAN_52_INFO { get; set; }
        public string LOAN_53_INFO { get; set; }
        public string LOAN_54_INFO { get; set; }
        public string LOAN_55_INFO { get; set; }
        public string LOAN_56_INFO { get; set; }
        public string LOAN_57_INFO { get; set; }
        public string LOAN_58_INFO { get; set; }
        public string LOAN_59_INFO { get; set; }
        public string LOAN_60_INFO { get; set; }
        public string LOAN_61_INFO { get; set; }
        public string LOAN_62_INFO { get; set; }
        public string LOAN_63_INFO { get; set; }
        public string LOAN_64_INFO { get; set; }
        public string LOAN_65_INFO { get; set; }
        public string LOAN_66_INFO { get; set; }
        public string LOAN_67_INFO { get; set; }
        public string LOAN_68_INFO { get; set; }
        public string LOAN_69_INFO { get; set; }
        public string LOAN_70_INFO { get; set; }
        public string LOAN_71_INFO { get; set; }
        public string LOAN_72_INFO { get; set; }
        public string LOAN_73_INFO { get; set; }
        public string LOAN_74_INFO { get; set; }
        public string LOAN_75_INFO { get; set; }
        public string LOAN_76_INFO { get; set; }
        public string LOAN_77_INFO { get; set; }
        public string LOAN_78_INFO { get; set; }
        public string LOAN_79_INFO { get; set; }
        public string LOAN_80_INFO { get; set; }
        public string LOAN_81_INFO { get; set; }
        public string LOAN_82_INFO { get; set; }
        public string LOAN_83_INFO { get; set; }
        public string LOAN_84_INFO { get; set; }
        public string LOAN_85_INFO { get; set; }
        public string LOAN_86_INFO { get; set; }
        public string LOAN_87_INFO { get; set; }
        public string LOAN_88_INFO { get; set; }
        public string LOAN_89_INFO { get; set; }
        public string LOAN_90_INFO { get; set; }
        public string LOAN_91_INFO { get; set; }
        public string LOAN_92_INFO { get; set; }
        public string LOAN_93_INFO { get; set; }
        public string LOAN_94_INFO { get; set; }
        public string LOAN_95_INFO { get; set; }
        public string LOAN_96_INFO { get; set; }
        public string LOAN_97_INFO { get; set; }
        public string LOAN_98_INFO { get; set; }
        public string LOAN_99_INFO { get; set; }
        public string LOAN_100_INFO { get; set; }
    }
}
