//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false, ElementName="result")]
public partial class OrderResult {
    
    private resultOrdersOrder[] ordersField;
    
    private string statusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("order", typeof(resultOrdersOrder), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public resultOrdersOrder[] orders {
        get {
            return this.ordersField;
        }
        set {
            this.ordersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrdersOrder {
    
    private string cardsField;
    
    private resultOrdersOrderCustomer[] customerField;
    
    private resultOrdersOrderLocations[] locationsField;
    
    private resultOrdersOrderRetailersRetailer[] retailersField;
    
    private resultOrdersOrderPaymentsPayment[] paymentsField;
    
    private string site_nameField;
    
    private string site_logo_urlField;
    
    private string site_identifierField;
    
    private string require_auth_trackerField;
    
    private string pnm_order_cridField;
    
    private string pnm_customer_languageField;
    
    private string pnm_order_identifierField;
    
    private string pnm_order_short_identifierField;
    
    private string site_order_keyField;
    
    private string order_createdField;
    
    private string order_statusField;
    
    private string order_amountField;
    
    private string order_currencyField;
    
    private string minimum_payment_amountField;
    
    private string minimum_payment_currencyField;
    
    private string order_typeField;
    
    private string order_is_standingField;
    
    private string order_tracking_urlField;
    
    private string pnm_balance_due_amountField;
    
    private string pnm_balance_due_currencyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cards {
        get {
            return this.cardsField;
        }
        set {
            this.cardsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public resultOrdersOrderCustomer[] customer {
        get {
            return this.customerField;
        }
        set {
            this.customerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("locations", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public resultOrdersOrderLocations[] locations {
        get {
            return this.locationsField;
        }
        set {
            this.locationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("retailer", typeof(resultOrdersOrderRetailersRetailer), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public resultOrdersOrderRetailersRetailer[] retailers {
        get {
            return this.retailersField;
        }
        set {
            this.retailersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("payment", typeof(resultOrdersOrderPaymentsPayment), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public resultOrdersOrderPaymentsPayment[] payments {
        get {
            return this.paymentsField;
        }
        set {
            this.paymentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string site_name {
        get {
            return this.site_nameField;
        }
        set {
            this.site_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string site_logo_url {
        get {
            return this.site_logo_urlField;
        }
        set {
            this.site_logo_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string site_identifier {
        get {
            return this.site_identifierField;
        }
        set {
            this.site_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string require_auth_tracker {
        get {
            return this.require_auth_trackerField;
        }
        set {
            this.require_auth_trackerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_order_crid {
        get {
            return this.pnm_order_cridField;
        }
        set {
            this.pnm_order_cridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_customer_language {
        get {
            return this.pnm_customer_languageField;
        }
        set {
            this.pnm_customer_languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_order_identifier {
        get {
            return this.pnm_order_identifierField;
        }
        set {
            this.pnm_order_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_order_short_identifier {
        get {
            return this.pnm_order_short_identifierField;
        }
        set {
            this.pnm_order_short_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string site_order_key {
        get {
            return this.site_order_keyField;
        }
        set {
            this.site_order_keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string order_created {
        get {
            return this.order_createdField;
        }
        set {
            this.order_createdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string order_status {
        get {
            return this.order_statusField;
        }
        set {
            this.order_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string order_amount {
        get {
            return this.order_amountField;
        }
        set {
            this.order_amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string order_currency {
        get {
            return this.order_currencyField;
        }
        set {
            this.order_currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minimum_payment_amount {
        get {
            return this.minimum_payment_amountField;
        }
        set {
            this.minimum_payment_amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minimum_payment_currency {
        get {
            return this.minimum_payment_currencyField;
        }
        set {
            this.minimum_payment_currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string order_type {
        get {
            return this.order_typeField;
        }
        set {
            this.order_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string order_is_standing {
        get {
            return this.order_is_standingField;
        }
        set {
            this.order_is_standingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string order_tracking_url {
        get {
            return this.order_tracking_urlField;
        }
        set {
            this.order_tracking_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_balance_due_amount {
        get {
            return this.pnm_balance_due_amountField;
        }
        set {
            this.pnm_balance_due_amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_balance_due_currency {
        get {
            return this.pnm_balance_due_currencyField;
        }
        set {
            this.pnm_balance_due_currencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrdersOrderCustomer {
    
    private string pnm_customer_identifierField;
    
    private string site_customer_identifierField;
    
    private string pnm_customer_addresseeField;
    
    private string pnm_customer_postal_codeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_customer_identifier {
        get {
            return this.pnm_customer_identifierField;
        }
        set {
            this.pnm_customer_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string site_customer_identifier {
        get {
            return this.site_customer_identifierField;
        }
        set {
            this.site_customer_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_customer_addressee {
        get {
            return this.pnm_customer_addresseeField;
        }
        set {
            this.pnm_customer_addresseeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_customer_postal_code {
        get {
            return this.pnm_customer_postal_codeField;
        }
        set {
            this.pnm_customer_postal_codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrdersOrderLocations {
    
    private resultOrdersOrderLocationsLocation[] locationField;
    
    private string latitudeField;
    
    private string longitudeField;
    
    private string map_urlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("location", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public resultOrdersOrderLocationsLocation[] location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string map_url {
        get {
            return this.map_urlField;
        }
        set {
            this.map_urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrdersOrderLocationsLocation {
    
    private string retailerField;
    
    private string streetField;
    
    private string cityField;
    
    private string stateField;
    
    private string latitudeField;
    
    private string longitudeField;
    
    private string distanceField;
    
    private string phoneField;
    
    private string pnm_retailer_identifierField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer {
        get {
            return this.retailerField;
        }
        set {
            this.retailerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_retailer_identifier {
        get {
            return this.pnm_retailer_identifierField;
        }
        set {
            this.pnm_retailer_identifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrdersOrderRetailersRetailer {
    
    private resultOrdersOrderRetailersRetailerFees[] feesField;
    
    private resultOrdersOrderRetailersRetailerSlip[] slipField;
    
    private resultOrdersOrderRetailersRetailerMobile[] mobileField;
    
    private string retailer_nameField;
    
    private string retailer_identifierField;
    
    private string retailer_logoField;
    
    private string retailer_mapkeyField;
    
    private string retailer_iconField;
    
    private string retailer_nicknameField;
    
    private string retailer_mobile_barcodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fees", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public resultOrdersOrderRetailersRetailerFees[] fees {
        get {
            return this.feesField;
        }
        set {
            this.feesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("slip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public resultOrdersOrderRetailersRetailerSlip[] slip {
        get {
            return this.slipField;
        }
        set {
            this.slipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mobile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public resultOrdersOrderRetailersRetailerMobile[] mobile {
        get {
            return this.mobileField;
        }
        set {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_name {
        get {
            return this.retailer_nameField;
        }
        set {
            this.retailer_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_identifier {
        get {
            return this.retailer_identifierField;
        }
        set {
            this.retailer_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_logo {
        get {
            return this.retailer_logoField;
        }
        set {
            this.retailer_logoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_mapkey {
        get {
            return this.retailer_mapkeyField;
        }
        set {
            this.retailer_mapkeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_icon {
        get {
            return this.retailer_iconField;
        }
        set {
            this.retailer_iconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_nickname {
        get {
            return this.retailer_nicknameField;
        }
        set {
            this.retailer_nicknameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_mobile_barcode {
        get {
            return this.retailer_mobile_barcodeField;
        }
        set {
            this.retailer_mobile_barcodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrdersOrderRetailersRetailerFees {
    
    private string order_has_pos_feeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string order_has_pos_fee {
        get {
            return this.order_has_pos_feeField;
        }
        set {
            this.order_has_pos_feeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrdersOrderRetailersRetailerSlip {
    
    private string full_encodingField;
    
    private string slip_urlField;
    
    private string slip_pdf_urlField;
    
    private string slip_idField;
    
    private string retailer_nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string full_encoding {
        get {
            return this.full_encodingField;
        }
        set {
            this.full_encodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string slip_url {
        get {
            return this.slip_urlField;
        }
        set {
            this.slip_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string slip_pdf_url {
        get {
            return this.slip_pdf_urlField;
        }
        set {
            this.slip_pdf_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string slip_id {
        get {
            return this.slip_idField;
        }
        set {
            this.slip_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_name {
        get {
            return this.retailer_nameField;
        }
        set {
            this.retailer_nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrdersOrderRetailersRetailerMobile {
    
    private string full_encodingField;
    
    private string barcode_urlField;
    
    private string retailer_nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string full_encoding {
        get {
            return this.full_encodingField;
        }
        set {
            this.full_encodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string barcode_url {
        get {
            return this.barcode_urlField;
        }
        set {
            this.barcode_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_name {
        get {
            return this.retailer_nameField;
        }
        set {
            this.retailer_nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrdersOrderPaymentsPayment {
    
    private resultOrdersOrderPaymentsPaymentMerchant_settlementsMerchant_settlement[] merchant_settlementsField;
    
    private string payment_madeField;
    
    private string payment_amountField;
    
    private string payment_currencyField;
    
    private string payment_statusField;
    
    private string net_payment_amountField;
    
    private string net_payment_currencyField;
    
    private string payment_processing_feeField;
    
    private string settled_to_siteField;
    
    private string date_settled_to_merchantField;
    
    private string pnm_payment_identifierField;
    
    private string retailer_identifierField;
    
    private string payment_receipt_textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("merchant_settlement", typeof(resultOrdersOrderPaymentsPaymentMerchant_settlementsMerchant_settlement), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public resultOrdersOrderPaymentsPaymentMerchant_settlementsMerchant_settlement[] merchant_settlements {
        get {
            return this.merchant_settlementsField;
        }
        set {
            this.merchant_settlementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string payment_made {
        get {
            return this.payment_madeField;
        }
        set {
            this.payment_madeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string payment_amount {
        get {
            return this.payment_amountField;
        }
        set {
            this.payment_amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string payment_currency {
        get {
            return this.payment_currencyField;
        }
        set {
            this.payment_currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string payment_status {
        get {
            return this.payment_statusField;
        }
        set {
            this.payment_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string net_payment_amount {
        get {
            return this.net_payment_amountField;
        }
        set {
            this.net_payment_amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string net_payment_currency {
        get {
            return this.net_payment_currencyField;
        }
        set {
            this.net_payment_currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string payment_processing_fee {
        get {
            return this.payment_processing_feeField;
        }
        set {
            this.payment_processing_feeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string settled_to_site {
        get {
            return this.settled_to_siteField;
        }
        set {
            this.settled_to_siteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string date_settled_to_merchant {
        get {
            return this.date_settled_to_merchantField;
        }
        set {
            this.date_settled_to_merchantField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_payment_identifier {
        get {
            return this.pnm_payment_identifierField;
        }
        set {
            this.pnm_payment_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_identifier {
        get {
            return this.retailer_identifierField;
        }
        set {
            this.retailer_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string payment_receipt_text {
        get {
            return this.payment_receipt_textField;
        }
        set {
            this.payment_receipt_textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrdersOrderPaymentsPaymentMerchant_settlementsMerchant_settlement {
    
    private string settlement_method_identifierField;
    
    private string settlement_typeField;
    
    private string settlement_amountField;
    
    private string settlement_currencyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string settlement_method_identifier {
        get {
            return this.settlement_method_identifierField;
        }
        set {
            this.settlement_method_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string settlement_type {
        get {
            return this.settlement_typeField;
        }
        set {
            this.settlement_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string settlement_amount {
        get {
            return this.settlement_amountField;
        }
        set {
            this.settlement_amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string settlement_currency {
        get {
            return this.settlement_currencyField;
        }
        set {
            this.settlement_currencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {

    private OrderResult[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("result")]
    public OrderResult[] Items
    {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
