//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false,ElementName="result")]
public partial class OrderCreate {
    
    private resultOrder orderField;
    
    private string statusField;
    
    /// <remarks/>
    public resultOrder order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrder {
    
    private object cardsField;
    
    private resultOrderCustomer customerField;
    
    private resultOrderLocations locationsField;
    
    private resultOrderRetailers retailersField;
    
    private string site_nameField;
    
    private string site_logo_urlField;
    
    private string site_identifierField;
    
    private bool require_auth_trackerField;
    
    private string pnm_order_cridField;
    
    private string pnm_customer_languageField;
    
    private ulong pnm_order_identifierField;
    
    private string pnm_order_short_identifierField;
    
    private string site_order_keyField;
    
    private string order_createdField;
    
    private string order_statusField;
    
    private decimal order_amountField;
    
    private string order_currencyField;
    
    private decimal minimum_payment_amountField;
    
    private string minimum_payment_currencyField;
    
    private string order_typeField;
    
    private bool order_is_standingField;
    
    private decimal pnm_balance_due_amountField;
    
    private string pnm_balance_due_currencyField;
    
    private string order_tracking_urlField;
    
    /// <remarks/>
    public object cards {
        get {
            return this.cardsField;
        }
        set {
            this.cardsField = value;
        }
    }
    
    /// <remarks/>
    public resultOrderCustomer customer {
        get {
            return this.customerField;
        }
        set {
            this.customerField = value;
        }
    }
    
    /// <remarks/>
    public resultOrderLocations locations {
        get {
            return this.locationsField;
        }
        set {
            this.locationsField = value;
        }
    }
    
    /// <remarks/>
    public resultOrderRetailers retailers {
        get {
            return this.retailersField;
        }
        set {
            this.retailersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string site_name {
        get {
            return this.site_nameField;
        }
        set {
            this.site_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string site_logo_url {
        get {
            return this.site_logo_urlField;
        }
        set {
            this.site_logo_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string site_identifier {
        get {
            return this.site_identifierField;
        }
        set {
            this.site_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool require_auth_tracker {
        get {
            return this.require_auth_trackerField;
        }
        set {
            this.require_auth_trackerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_order_crid {
        get {
            return this.pnm_order_cridField;
        }
        set {
            this.pnm_order_cridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_customer_language {
        get {
            return this.pnm_customer_languageField;
        }
        set {
            this.pnm_customer_languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong pnm_order_identifier {
        get {
            return this.pnm_order_identifierField;
        }
        set {
            this.pnm_order_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_order_short_identifier {
        get {
            return this.pnm_order_short_identifierField;
        }
        set {
            this.pnm_order_short_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string site_order_key {
        get {
            return this.site_order_keyField;
        }
        set {
            this.site_order_keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string order_created {
        get {
            return this.order_createdField;
        }
        set {
            this.order_createdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string order_status {
        get {
            return this.order_statusField;
        }
        set {
            this.order_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal order_amount {
        get {
            return this.order_amountField;
        }
        set {
            this.order_amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string order_currency {
        get {
            return this.order_currencyField;
        }
        set {
            this.order_currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal minimum_payment_amount {
        get {
            return this.minimum_payment_amountField;
        }
        set {
            this.minimum_payment_amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minimum_payment_currency {
        get {
            return this.minimum_payment_currencyField;
        }
        set {
            this.minimum_payment_currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string order_type {
        get {
            return this.order_typeField;
        }
        set {
            this.order_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool order_is_standing {
        get {
            return this.order_is_standingField;
        }
        set {
            this.order_is_standingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal pnm_balance_due_amount {
        get {
            return this.pnm_balance_due_amountField;
        }
        set {
            this.pnm_balance_due_amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_balance_due_currency {
        get {
            return this.pnm_balance_due_currencyField;
        }
        set {
            this.pnm_balance_due_currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string order_tracking_url {
        get {
            return this.order_tracking_urlField;
        }
        set {
            this.order_tracking_urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrderCustomer {
    
    private string pnm_customer_identifierField;
    
    private string site_customer_identifierField;
    
    private string pnm_customer_addresseeField;
    
    private string pnm_customer_postal_codeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_customer_identifier {
        get {
            return this.pnm_customer_identifierField;
        }
        set {
            this.pnm_customer_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string site_customer_identifier {
        get {
            return this.site_customer_identifierField;
        }
        set {
            this.site_customer_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_customer_addressee {
        get {
            return this.pnm_customer_addresseeField;
        }
        set {
            this.pnm_customer_addresseeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_customer_postal_code {
        get {
            return this.pnm_customer_postal_codeField;
        }
        set {
            this.pnm_customer_postal_codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrderLocations {
    
    private resultOrderLocationsLocation[] locationField;
    
    private decimal latitudeField;
    
    private decimal longitudeField;
    
    private string map_urlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("location")]
    public resultOrderLocationsLocation[] location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string map_url {
        get {
            return this.map_urlField;
        }
        set {
            this.map_urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrderLocationsLocation {
    
    private string retailerField;
    
    private string streetField;
    
    private string cityField;
    
    private string stateField;
    
    private decimal latitudeField;
    
    private decimal longitudeField;
    
    private decimal distanceField;
    
    private string phoneField;
    
    private string pnm_retailer_identifierField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer {
        get {
            return this.retailerField;
        }
        set {
            this.retailerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pnm_retailer_identifier {
        get {
            return this.pnm_retailer_identifierField;
        }
        set {
            this.pnm_retailer_identifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrderRetailers {
    
    private resultOrderRetailersRetailer retailerField;
    
    /// <remarks/>
    public resultOrderRetailersRetailer retailer {
        get {
            return this.retailerField;
        }
        set {
            this.retailerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrderRetailersRetailer {
    
    private resultOrderRetailersRetailerFees feesField;
    
    private resultOrderRetailersRetailerSlip slipField;
    
    private resultOrderRetailersRetailerMobile mobileField;
    
    private string retailer_nameField;
    
    private string retailer_identifierField;
    
    private string retailer_logoField;
    
    private string retailer_mapkeyField;
    
    private string retailer_iconField;
    
    private string retailer_nicknameField;
    
    private bool retailer_mobile_barcodeField;
    
    /// <remarks/>
    public resultOrderRetailersRetailerFees fees {
        get {
            return this.feesField;
        }
        set {
            this.feesField = value;
        }
    }
    
    /// <remarks/>
    public resultOrderRetailersRetailerSlip slip {
        get {
            return this.slipField;
        }
        set {
            this.slipField = value;
        }
    }
    
    /// <remarks/>
    public resultOrderRetailersRetailerMobile mobile {
        get {
            return this.mobileField;
        }
        set {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_name {
        get {
            return this.retailer_nameField;
        }
        set {
            this.retailer_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_identifier {
        get {
            return this.retailer_identifierField;
        }
        set {
            this.retailer_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_logo {
        get {
            return this.retailer_logoField;
        }
        set {
            this.retailer_logoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_mapkey {
        get {
            return this.retailer_mapkeyField;
        }
        set {
            this.retailer_mapkeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_icon {
        get {
            return this.retailer_iconField;
        }
        set {
            this.retailer_iconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_nickname {
        get {
            return this.retailer_nicknameField;
        }
        set {
            this.retailer_nicknameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool retailer_mobile_barcode {
        get {
            return this.retailer_mobile_barcodeField;
        }
        set {
            this.retailer_mobile_barcodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrderRetailersRetailerFees {
    
    private bool order_has_pos_feeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool order_has_pos_fee {
        get {
            return this.order_has_pos_feeField;
        }
        set {
            this.order_has_pos_feeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrderRetailersRetailerSlip {
    
    private string full_encodingField;
    
    private string slip_urlField;
    
    private string slip_pdf_urlField;
    
    private ulong slip_idField;
    
    private string retailer_nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string full_encoding {
        get {
            return this.full_encodingField;
        }
        set {
            this.full_encodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string slip_url {
        get {
            return this.slip_urlField;
        }
        set {
            this.slip_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string slip_pdf_url {
        get {
            return this.slip_pdf_urlField;
        }
        set {
            this.slip_pdf_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong slip_id {
        get {
            return this.slip_idField;
        }
        set {
            this.slip_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_name {
        get {
            return this.retailer_nameField;
        }
        set {
            this.retailer_nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class resultOrderRetailersRetailerMobile {
    
    private string full_encodingField;
    
    private string barcode_urlField;
    
    private string retailer_nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string full_encoding {
        get {
            return this.full_encodingField;
        }
        set {
            this.full_encodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string barcode_url {
        get {
            return this.barcode_urlField;
        }
        set {
            this.barcode_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retailer_name {
        get {
            return this.retailer_nameField;
        }
        set {
            this.retailer_nameField = value;
        }
    }
}
