//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Pay.
        /// </summary>
        internal static string AddPay {
            get {
                return ResourceManager.GetString("AddPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Date.
        /// </summary>
        internal static string ApproveDate {
            get {
                return ResourceManager.GetString("ApproveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samity ID.
        /// </summary>
        internal static string CenterID {
            get {
                return ResourceManager.GetString("CenterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Drop.
        /// </summary>
        internal static string ContinuousDrop {
            get {
                return ResourceManager.GetString("ContinuousDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        internal static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disburse Date.
        /// </summary>
        internal static string DisburseDate {
            get {
                return ResourceManager.GetString("DisburseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropInstallment.
        /// </summary>
        internal static string DropInstallment {
            get {
                return ResourceManager.GetString("DropInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Address.
        /// </summary>
        internal static string EmpAddress {
            get {
                return ResourceManager.GetString("EmpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Code.
        /// </summary>
        internal static string EmployeeCode {
            get {
                return ResourceManager.GetString("EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        internal static string EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Status.
        /// </summary>
        internal static string EmployeeStatus {
            get {
                return ResourceManager.GetString("EmployeeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        internal static string EmpName {
            get {
                return ResourceManager.GetString("EmpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name (Unicode).
        /// </summary>
        internal static string EmpNameBen {
            get {
                return ResourceManager.GetString("EmpNameBen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grace Period.
        /// </summary>
        internal static string GracePeriod {
            get {
                return ResourceManager.GetString("GracePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Name.
        /// </summary>
        internal static string GuardianName {
            get {
                return ResourceManager.GetString("GuardianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays.
        /// </summary>
        internal static string Holidays {
            get {
                return ResourceManager.GetString("Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Date.
        /// </summary>
        internal static string InstallmentDate {
            get {
                return ResourceManager.GetString("InstallmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment No.
        /// </summary>
        internal static string InstallmentNo {
            get {
                return ResourceManager.GetString("InstallmentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment StartDate.
        /// </summary>
        internal static string InstallmentStartDate {
            get {
                return ResourceManager.GetString("InstallmentStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance ItemCode.
        /// </summary>
        internal static string InsuranceItemCode {
            get {
                return ResourceManager.GetString("InsuranceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance ItemRate.
        /// </summary>
        internal static string InsuranceItemRate {
            get {
                return ResourceManager.GetString("InsuranceItemRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC Charge.
        /// </summary>
        internal static string IntCharge {
            get {
                return ResourceManager.GetString("IntCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC Calculation Method.
        /// </summary>
        internal static string InterestCalculationMethod {
            get {
                return ResourceManager.GetString("InterestCalculationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC Installment.
        /// </summary>
        internal static string InterestInstallment {
            get {
                return ResourceManager.GetString("InterestInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC Rate.
        /// </summary>
        internal static string InterestRate {
            get {
                return ResourceManager.GetString("InterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC Installment.
        /// </summary>
        internal static string IntInstallment {
            get {
                return ResourceManager.GetString("IntInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC Paid.
        /// </summary>
        internal static string IntPaid {
            get {
                return ResourceManager.GetString("IntPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investor.
        /// </summary>
        internal static string Investor {
            get {
                return ResourceManager.GetString("Investor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investor Code.
        /// </summary>
        internal static string InvestorCode {
            get {
                return ResourceManager.GetString("InvestorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investor ID.
        /// </summary>
        internal static string InvestorID {
            get {
                return ResourceManager.GetString("InvestorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Br.Joining Date.
        /// </summary>
        internal static string JoiningDate {
            get {
                return ResourceManager.GetString("JoiningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan CloseDate.
        /// </summary>
        internal static string LoanCloseDate {
            get {
                return ResourceManager.GetString("LoanCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Installment.
        /// </summary>
        internal static string LoanInstallment {
            get {
                return ResourceManager.GetString("LoanInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Repaid.
        /// </summary>
        internal static string LoanRepaid {
            get {
                return ResourceManager.GetString("LoanRepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Status.
        /// </summary>
        internal static string LoanStatus {
            get {
                return ResourceManager.GetString("LoanStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoanSummary ID.
        /// </summary>
        internal static string LoanSummaryID {
            get {
                return ResourceManager.GetString("LoanSummaryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Term.
        /// </summary>
        internal static string LoanTerm {
            get {
                return ResourceManager.GetString("LoanTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainItemName.
        /// </summary>
        internal static string MainItemName {
            get {
                return ResourceManager.GetString("MainItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainProductCode.
        /// </summary>
        internal static string MainProductCode {
            get {
                return ResourceManager.GetString("MainProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Limit.
        /// </summary>
        internal static string MaxLimit {
            get {
                return ResourceManager.GetString("MaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberCategory ID.
        /// </summary>
        internal static string MemberCategoryID {
            get {
                return ResourceManager.GetString("MemberCategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Category Name.
        /// </summary>
        internal static string MemberCategoryName {
            get {
                return ResourceManager.GetString("MemberCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID.
        /// </summary>
        internal static string MemberID {
            get {
                return ResourceManager.GetString("MemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Limit.
        /// </summary>
        internal static string MinLimit {
            get {
                return ResourceManager.GetString("MinLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoOfAccount.
        /// </summary>
        internal static string NoOfAccount {
            get {
                return ResourceManager.GetString("NoOfAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office ID.
        /// </summary>
        internal static string OfficeID {
            get {
                return ResourceManager.GetString("OfficeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue Date.
        /// </summary>
        internal static string OverdueDate {
            get {
                return ResourceManager.GetString("OverdueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        internal static string PassBookStartDate {
            get {
                return ResourceManager.GetString("PassBookStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Frequency.
        /// </summary>
        internal static string PaymentFrequency {
            get {
                return ResourceManager.GetString("PaymentFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No.
        /// </summary>
        internal static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Loan.
        /// </summary>
        internal static string PrincipalLoan {
            get {
                return ResourceManager.GetString("PrincipalLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        internal static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name (Unicode).
        /// </summary>
        internal static string ProductFullNameBng {
            get {
                return ResourceManager.GetString("ProductFullNameBng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductName English .
        /// </summary>
        internal static string ProductFullNameEng {
            get {
                return ResourceManager.GetString("ProductFullNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        internal static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Short Name (Unicode).
        /// </summary>
        internal static string ProductShortNameBng {
            get {
                return ResourceManager.GetString("ProductShortNameBng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        internal static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose ID.
        /// </summary>
        internal static string PurposeID {
            get {
                return ResourceManager.GetString("PurposeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        internal static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings Installment.
        /// </summary>
        internal static string SavingsInstallment {
            get {
                return ResourceManager.GetString("SavingsInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavingSummary ID.
        /// </summary>
        internal static string SavingSummaryID {
            get {
                return ResourceManager.GetString("SavingSummaryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        internal static string TransType {
            get {
                return ResourceManager.GetString("TransType", resourceCulture);
            }
        }
    }
}
