//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BKashAPILOG
    {
        public long ID { get; set; }
        public string AccountNo { get; set; }
        public Nullable<System.DateTime> BillMonth { get; set; }
        public decimal Amount { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ProdType { get; set; }
        public Nullable<long> SummaryID { get; set; }
        public string TranType { get; set; }
        public string Media { get; set; }
        public string TrxId { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<decimal> IntAmount { get; set; }
        public string MemberPhoneNo { get; set; }
    }
}
