//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BKashAPIParking
    {
        public long ID { get; set; }
        public string AccountNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public decimal Amount { get; set; }
        public string MobileNo { get; set; }
        public string TrxId { get; set; }
        public int RequestFor { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string MessageResponse { get; set; }
        public string MemberPhoneNo { get; set; }
    }
}
